services:
  routemaster_api:
    build: ./Furkan-Çağrı-Başkan/Web/routemaster-backend
    container_name: routemasterapi_kapsayici
    ports:
      - "3000:3000"
    networks:
      - routemaster_ag
    restart: always
    depends_on:
      - mongo
      - redis
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://mongodb_kapsayici:27017/routemasterdb
      - REDIS_URL=redis://redis_kapsayici:6379
      - RABBITMQ_URL=amqp://rabbitmq_kapsayici:5672
    command: npm start

  mongo:
    image: mongo:latest
    container_name: mongodb_kapsayici
    networks:
      - routemaster_ag
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  redis:
    image: redis:latest
    container_name: redis_kapsayici
    networks:
      - routemaster_ag
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_kapsayici
    networks:
      - routemaster_ag
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

# İşte unutulan o sihirli bağlantı noktası:
networks:
  routemaster_ag:
    driver: bridge